awesomeyap/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('nav/', include('navigation.urls')),
    path('admin/', admin.site.urls),
]

navigation/urls.py
from django.urls import path

from . import views

app_name = 'navigation'
urlpatterns = [
    path('', views.index, name='index'),
    path('soup', views.soup, name='soup'),
    path('list', views.list, name='list'),
    path('update', views.update, name='update')
]

navigation/models.py
from django.db import models

class Post(models.Model):
    rating = models.IntegerField(default=0)
    link = models.URLField(primary_key=True)
    title = models.CharField(max_length=200)
    image_src = models.URLField(blank=True, default='')
    author = models.CharField(max_length=100)
    section = models.CharField(max_length=50)
    date = models.DateField()
    comments = models.IntegerField(default=0)
    excerpt = models.TextField()
    content = models.TextField()

navigation/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from .scrap import get_front_page_posts
from navigation.models import Post

def index(request):
    template = loader.get_template('navigation/index.html')
    return HttpResponse(template.render({}, request))

def list(request):
    posts = Post.objects.order_by('-rating')
    template = loader.get_template('navigation/list.html')
    return HttpResponse(template.render({'posts':posts}, request))

def update(request):
    posts = get_front_page_posts()
    for p in posts:
        post = Post(rating = p['rating'],
                    link = p['link'],
                    title = p['title'],
                    image_src = p['image_src'],
                    author = p['author'],
                    section = p['section'],
                    date = p['date'],
                    comments = p['comments'],
                    excerpt = p['excerpt'],
                    content = p['content'])
        post.save()
    return HttpResponseRedirect(reverse('navigation:list'))

def soup(request):
    posts = get_front_page_posts()
    for p in posts:
        post = Post(rating = p['rating'],
                    link = p['link'],
                    title = p['title'],
                    image_src = p['image_src'],
                    author = p['author'],
                    section = p['section'],
                    date = p['date'],
                    comments = p['comments'],
                    excerpt = p['excerpt'],
                    content = p['content'])
        post.save()
    template = loader.get_template('navigation/posts.html')
    return HttpResponse(template.render({'posts':posts}, request))

navigation/templates/navigation/index.html
<h1>Do you want soup?</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'navigation:soup' %}" method="post">
{% csrf_token %}
<input type="submit" value="Soup!">
</form>

navigation/templates/navigation/list.html
{% load static %}
<link href='https://fonts.googleapis.com/css?family=Roboto+Condensed:700' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Vollkorn:400,400italic,900' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="{% static 'css/style.css' %}" />
<main class="main-area">
    <section class="cards centered">
    {% for post in posts %}
        {% if post.image_src|length > 0 %}
            <article class="card">
                <div class="card-thumbnail">
                    <a href="{{ post.link }}">
                        <figure class="thumbnail">
                            <img src="{{ post.image_src }}" alt="">
                        </figure>
                    </a>
                </div>
                <div class="card-content">
                    <a href="{{ post.link }}">
                        <h1>{{ post.title }}</h1>
                    </a>
                    <p>{{ post.excerpt|truncatewords:15 }}</p>
                </div>
            </article>
        {% endif %}
    {% endfor %}

navigation/templates/navigation/posts.html
<h1>Posts</h1>

<ul>
{% for post in posts %}
    <li>{{ post.rating }} -- {{ post.title }}</li>
{% endfor %}
</ul>